Task about mass calculation of cabinet
alvls/mp1-2023-2 pull request #17
Opened 2023-09-30 19:35 UTC by VALancaster

2023-10-04 11:20 UTC, alvls commented
Валентин, у вас не подключен файл Source.c в проект task1. Нужно исправить.

2023-10-04 13:26 UTC, VALancaster reviewed
Задание 0 и Задание 1 выполнено не в Visual Studio

2023-10-04 13:44 UTC, alvls requested changes

2023-10-04 13:44 UTC, alvls commented on kutergin_vt/task1/Source1.c
> +    scanf("%d %d %d", &DVP, &DSP, &wood);
Нежелательно просить пользователя вводить плотности, лучше "зашить" их в программе.

2023-10-04 14:36 UTC, VALancaster commented
Обновил с учетом объявления плотностей, "зашивания" в коде программы

2023-10-04 20:11 UTC, alvls commented
![изображение](https://github.com/alvls/mp1-2023-2/assets/5449780/bc06d617-849b-49f2-88fe-1715ec3e6c8d)
При типовых размерах шкафа, его вес получается раз в 3 меньше, чем должен быть. У вас где-то ошибка в вычислениях.

2023-10-04 21:30 UTC, VALancaster commented
Проверил вычисления, ошибки нет в них. Заметил, что при вводе d = 0,5 (с запятой), d расценивается как 0 и массы трех деталей зануляются, поэтому вес получается в три раза меньший. При вводе же d = 0.5 (с точкой), все хорошо считается. 
<img width="440" alt="Снимок экрана 2023-10-05 в 00 30 17" src="https://github.com/alvls/mp1-2023-2/assets/144248381/ec3ecb5f-44f1-41ad-bf42-49545bbdd8b3">

2023-10-05 06:01 UTC, alvls commented
> Проверил вычисления, ошибки нет в них. Заметил, что при вводе d = 0,5 (с запятой), d расценивается как 0 и массы трех деталей зануляются, поэтому вес получается в три раза меньший. При вводе же d = 0.5 (с точкой), все хорошо считается. 

Действительно, так. Хорошо, вопрос снимается.

| Работа принята            |      |
| ------------------------- | ---- |
| __Ваш текущий  балл:__    |      |
| Функциональность:         | 3,0  |
| Качество  проектирования: | 1,5  |
| Качество  кода:           | 1,5  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 6,0  |

2023-10-05 06:02 UTC, merged