Task 1 completed
alvls/mp1-2023-2 pull request #23
Opened 2023-10-03 19:10 UTC by smallAbyss

2023-10-04 13:55 UTC, alvls requested changes

2023-10-07 16:20 UTC, smallAbyss commented
Исправил, теперь там отдельные проверки

2023-10-10 19:37 UTC, smallAbyss commented
Не знаю, можно ли делать 2 pull-request одновременно, потому task2 тоже пока будет здесь, просто для даты

2023-10-11 11:00 UTC, alvls commented
По заданию 1 все ок. На будущее - желательно вносить правки по замечаниям побыстрее.
| Работа  принята           |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 3,0  |
| Качество  проектирования: | 1,5  |
| Качество кода:            | 1,5  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 6,0  |

2023-10-11 14:15 UTC, alvls requested changes

2023-10-11 14:15 UTC, alvls commented on Luzan_EA/task2/Source.c
> +
Многовато пустых строк. Достаточно одной.

2023-10-11 14:15 UTC, alvls commented on Luzan_EA/task2/Source.c
> +
См. выше

2023-10-11 14:15 UTC, alvls commented on Luzan_EA/task2/Source.c
> +
И снова

2023-10-11 14:15 UTC, alvls commented on Luzan_EA/task2/Source.c
> +
И еще раз

2023-10-11 14:15 UTC, alvls commented on Luzan_EA/task2/Source.c
> +void main() {
Скобку перенести на след. строку.

2023-10-11 14:15 UTC, alvls commented on Luzan_EA/task2/Source.c
> +
Пустую строку удалить

2023-10-11 14:15 UTC, alvls commented on Luzan_EA/task2/Source.c
> +
Оставить одну пустую строку

2023-10-11 14:15 UTC, alvls commented on Luzan_EA/task2/Source.c
> +
Удалить пустые строки

2023-10-11 14:15 UTC, alvls commented on Luzan_EA/task2/Source.c
> +	printf_s("Hello, what mode do you want to play?\n");
Неплохо бы подсказать, какие режимы доступны

2023-10-11 14:15 UTC, alvls commented on Luzan_EA/task2/Source.c
> +		printf_s("Enter 'l' if you want to leave and '1' or '2' if you want to play again\n");
Старайтесь использовать хорошо различимые символы. l и 1 очень похожи во многих шрифтах.

2023-10-13 19:59 UTC, smallAbyss commented
Замечания исправил, впредь постараюсь быть оперативнее

2023-10-13 19:59 UTC, smallAbyss commented on Luzan_EA/task2/Source.c
> +		printf_s("Enter 'l' if you want to leave and '1' or '2' if you want to play again\n");
Исправил

2023-10-18 10:18 UTC, merged