Completed task about eletronic cash register
alvls/mp1-2023-2 pull request #54
Opened 2023-10-27 12:02 UTC by VALancaster

2023-10-27 12:02 UTC, VALancaster commented
Задание выполнено в Xcode

2023-11-08 10:22 UTC, alvls requested changes

2023-11-08 10:22 UTC, alvls commented on kutergin_vt/task4/main.c
> +struct Apple_Store iPhone12 = {3199, "iPhone 12 64GB", 70000, 10}; // 2-ой товар
Если все эти объекты "положить" в массив, то можно существенно простить функции ниже.

2023-11-08 10:22 UTC, alvls commented on kutergin_vt/task4/main.c
> +    while (b != 0) { // 0 - вывод чека
Переменная b не инициализирована

2023-11-08 10:24 UTC, alvls requested changes

2023-11-08 10:24 UTC, alvls commented on kutergin_vt/task4/main.c
> +    int barcode; // штрихкод
По  условию штрих-код должен храниться в массиве.

2023-11-08 10:24 UTC, alvls commented
Валентин, я могу оценить текущий вариант. Или вы можете переделать на использование массивов. Что выбираете?

2023-11-09 07:57 UTC, alvls commented
| Работа  принята           |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 4,0  |
| Качество  проектирования: | 1,8  |
| Качество кода:            | 2,0  |
| Бонус:                    | 0,2  |
| Штраф:                    | 0,0  |
| __Итого:__                | 8,0  |

Бонус за структуры. Минус за отсутствие массива товаров и сложный код из-за этого.

2023-11-09 13:53 UTC, merged