Task5
alvls/mp1-2023-2 pull request #84
Opened 2023-11-29 12:34 UTC by userskins

2023-12-04 19:23 UTC, alvls requested changes

2023-12-04 19:23 UTC, alvls commented on gusev_da/task5/task5.c
> +    begin = clock();
В замер времени должны входить только сортировки, а у вас входит ввод данных от пользователя. Исправьте

2023-12-04 19:27 UTC, userskins commented on gusev_da/task5/task5.c
> +    begin = clock();
Хорошо, сейчас поправлю

2023-12-05 06:24 UTC, alvls commented
| Работа  принята           |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 6,0  |
| Качество  проектирования: | 3,0  |
| Качество кода:            | 3,0  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 12,0 |

2023-12-05 08:36 UTC, closed without merging